komga:
  filesystem-scanner-force-directory-modified-time: false
  remember-me:
    key: changeMe!
    validity: 2592000 # 1 month
#  libraries-scan-cron: "*/5 * * * * ?" #every 5 seconds
  libraries-scan-cron: "-" #disable
  libraries-scan-startup: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        session.events.log: false
        format_sql: true
  artemis:
    embedded:
      data-directory: ./artemis
logging:
  file:
    max-history: 1
    name: komga-dev.log
  level:
    org.apache.activemq.audit.message: WARN
    org.jooq: DEBUG
#    web: DEBUG
#    org.gotson.komga: DEBUG
#    org.springframework.jms: DEBUG
#    org.springframework.security.web.FilterChainProxy: DEBUG
#    org.hibernate.stat: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.cache: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management.metrics.export.influx:
  #  enabled: true
  uri: http://localhost:8086

springdoc:
  cache:
    disabled: true

#server:
#  servlet:
#    context-path: /komga
